### ISSUE TITLE
[Admin] Changing fonts

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#80]
**Describe the solution/feature**
Activating the new licensed fonts (Unica77) within the admin tool. The typeface cuts have been added to the folder `shared/assets/fonts` and can linked (without copying it to a separate folder). 

See also example code for the UI tool: https://github.com/socialincome-san/public/blob/main/ui/src/main.css#L18

**Comment by yunsuklee** [comment]
Can I be assigned this issue?

**Comment by yunsuklee** [comment]
Hi, where should I add the new font?

**Comment by ssandino** [comment]
Just reference it (you can leave the font where it is). 

See also here: https://github.com/socialincome-san/public/blob/main/ui/src/main.css#L18 (other react app on the repo, who does it already)

**Comment by yunsuklee** [comment]
I'm afraid I'm not following what it is to be done.
I'm sorry, I do not wish to waste your time :c

**Comment by Ilikepizza2** [comment]
Okay may I be assigned this issue?

**Comment by Ilikepizza2** [comment]
Hello there!
So from what I can infer from seeing the project, is that there is a Unica77 font to be activated in /admin.
There is a Typography.tsx component which is a wrapper component for this font. So may I know that do I need to use this component in /admin or do I need to reference the font separately in /admin? Or am I getting this all wrong?

**Comment by ssandino** [comment]
Yes, you are getting it right. The admin tool should display the Unica77 font (instead of current `font-family` Rubik). There are two ways to do it:

A) Preferred Way: If you keep the actual font in the `shared/assets/fonts` and make it work with the `@font-face` rule (like it's done [here](https://github.com/socialincome-san/public/blob/main/ui/src/main.css#L18 – this is not linked to the admin tool, but is only an example of how we used `@font-face` rule in another project, which only refers to the font)). Not sure about the typography.tsx, sorry. But if it does the job then fine. 

B) Alternative: If you copy the fonts from the `shared/assets/fonts` into whatever folder it has to be in the admin tool (so `admin/something`).

**Comment by Ilikepizza2** [comment]
Well... there is no css file or tailwind config file in the /admin folder. My best guess would be that it is utilizing the /ui folder or something else for it's styling. Is that so?

**Comment by ssandino** [comment]
@renestalder any thoughts on this?

**Comment by renestalder** [comment]
If you want to use the fonts in the admin, create own `@font-face` definitions in the admin project's CSS (if there is no CSS file yet, check with @andrashee).

The font-face definition (apply correct relative path based on the location of the CSS file in the admin project):

```css
	@font-face {
		font-family: 'SoSans';
		font-weight: normal;
		src: url('../../shared/assets/fonts/Unica77LLWeb-Regular.woff2') format('woff2');
	}

	@font-face {
		font-family: 'SoSans';
		font-weight: 500;
		src: url('../../shared/assets/fonts/Unica77LLWeb-Medium.woff2') format('woff2');
	}

	@font-face {
		font-family: 'SoSans';
		font-weight: 700;
		src: url('../../shared/assets/fonts/Unica77LLWeb-Bold.woff2') format('woff2');
	}

	html {
		font-family: 'SoSans', system-ui, sans-serif;
	}
```
