### ISSUE TITLE
[Admin/Backend] Ensure deployments only happen on main branch

### ISSUE THREAD

**Issue by renestalder** [socialincome-san/public#90]
The current config is an OR condition:

```yml
on:
  push:
    branches:
      - main
    paths:
      - "admin/**"
      - "shared/**"
```

This means, the deployment happens either on the main branch or on changes in one of the defined paths.

As far as I can see, there is only one deployment channel open, and that is a public release. Therefore, any PR/branches that have changes in these folders create a productive deployment currently, no matter on what branch they happen.

I guess that was not the wanted behavior?
